# Generated by Django 5.0.6 on 2024-07-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='whatsapp',
            new_name='github',
        ),
    ]
