# Generated by Django 5.0.6 on 2024-07-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_whatsapp_user_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
    ]
