# Generated by Django 5.0.6 on 2024-07-30 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_address_contact_fax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='slug',
        ),
    ]
