# Generated by Django 5.0.6 on 2024-08-02 13:44

import django.core.validators
import painless.models.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contact_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[painless.models.validations.validate_phone_number]),
        ),
    ]
