# Generated by Django 5.0.6 on 2024-07-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('contact', models.TextField(max_length=225)),
            ],
            options={
                'verbose_name': 'services',
                'verbose_name_plural': 'service',
                'ordering': ['title'],
                'get_latest_by': ['-published_at'],
            },
        ),
    ]
