# Generated by Django 5.0.6 on 2024-07-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': ['-published_at'], 'ordering': ['-published_at', 'title'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-published_at'], 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '-----'), (1, 'Send'), (2, 'Cancel')], default=0, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='tag',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '-----'), (1, 'Send'), (2, 'Cancel')], default=0, verbose_name='Status'),
        ),
    ]
