# Generated by Django 5.0.6 on 2024-07-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myport', '0002_port_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='link',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
