# Generated by Django 5.0.6 on 2024-07-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myport', '0003_port_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='content',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
