# Generated by Django 5.0.6 on 2024-08-06 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myport', '0004_port_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'category',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='myport_cate_name_08ffa4_idx')],
            },
        ),
        migrations.AddField(
            model_name='port',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myport.category'),
            preserve_default=False,
        ),
    ]
