# Generated by Django 5.0.6 on 2024-08-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myport', '0005_category_port_category'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='myport_cate_name_08ffa4_idx',
        ),
    ]
