# Generated by Django 5.0.6 on 2024-08-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myport', '0006_remove_category_myport_cate_name_08ffa4_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'category', 'verbose_name_plural': 'category'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='port',
            old_name='slug',
            new_name='name',
        ),
    ]
