# Generated by Django 5.0.6 on 2024-08-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myport', '0007_alter_category_options_rename_name_category_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
