# Generated by Django 5.0.6 on 2024-07-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EXPERIENCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('datetime_year', models.IntegerField()),
            ],
            options={
                'verbose_name': 'EXPERIENCES',
                'verbose_name_plural': 'EXPERIENCE',
                'ordering': ['title'],
                'get_latest_by': ['-published_at'],
            },
        ),
    ]
