# Generated by Django 5.0.6 on 2024-08-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Experience', '0002_alter_experience_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='content',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
